name: iris-feature-and-prediction-pipelines

on:
  workflow_dispatch:
#  schedule:
#    - cron: '11 11 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.1'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute python workflows from bash script
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: ./src/01-module/scripts/run-feature-and-prediction-pipelines.sh

      - name: publish github pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated graph published"
      
          # Optional. Local and remote branch name where commit is going to be pushed
          #  to. Defaults to the current branch.
          #  You might need to set `create_branch: true` if the branch does not exist.
          branch: main
 
          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff'
      
          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          file_pattern: assets/latest_iris.png assets/actual_iris.png assets/confusion_matrix.png assets/df_recent.png
      
          # Optional. Local file path to the repository.
          # Defaults to the root of the repository.
          repository: .
      
          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
          commit_user_email: my-github-actions-bot@example.org # defaults to "github-actions[bot]@users.noreply.github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
      
          # Optional. Tag name being created in the local repository and 
          # pushed to remote repository and defined branch.
          #tagging_message: 'v1.0.0'
      
          # Optional. Option used by `git-status` to determine if the repository is 
          # dirty. See https://git-scm.com/docs/git-status#_options
          #status_options: '--untracked-files=no'
      
          # Optional. Options used by `git-add`.
          # See https://git-scm.com/docs/git-add#_options
          #add_options: '-u'
      
          # Optional. Options used by `git-push`.
          # See https://git-scm.com/docs/git-push#_options
          #push_options: '--force'
          
          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true 
          
          # Optional. Skip internal call to `git fetch`
          skip_fetch: false
          
          # Optional. Skip internal call to `git checkout`
          skip_checkout: false
      
          # Optional. Prevents the shell from expanding filenames. 
          # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
          disable_globbing: true
      
          # Optional. Create given branch name in local and remote repository.
          create_branch: false

